name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: |
        sudo apt install gcc-arm-none-eabi
        cd ./code/automated_test/gcc
        make clean
        make
        make clean

